export const BACKDROP = 'rgba(0, 0, 0, 0.4)'
/**
 * Blue when used as a background.
 */
export const BACKGROUND_BLUE = '#4285B9'
/**
 * Black when used as a background.
 */
export const BACKGROUND_BLACK = '#000000'
/**
 * White when used as a background.
 */
export const BACKGROUND_WHITE = '#FFFFFF'
export const BACKGROUND_WHITE_TRANSPARENT95 = 'rgba(255,255,255,0.95)'
export const BACKGROUND_LIGHTEST_WHITE = '#F2F2F2'
export const BACKGROUND_NEAR_WHITE = '#EFEFEF'
export const BACKGROUND_RED = '#E14F51'
export const BORDER_WHITE = '#FFFFFF'
export const BORDER_NEAR_WHITE = '#DDD'
export const BORDER_GRAY = '#E0D3D3'
export const FUN_BLUE = '#294f93'
export const AVATAR_BG = '#b87763'
export const BLUE_MEDIUM_DARK = '#294F93'
export const BLUE_DARK = '#2E4674'
export const BLUE_LIGHTEST = '#F4F6FA'
export const BLUE_LIGHT = '#267ADB'
export const BLUE_GRAY = '#50668F'
export const GRAY_MEDIUM_LIGHT = '#BCBCBC'
export const GRAY_DARK = '#4E4E4E'
export const GRAY_DARKER = '#D0C1C1'
export const GRAY_MEDIUM = '#F5F5F5'
export const GRAY_D9 = '#D9D9D9'
export const GRAY_LIGHT = '#CDCDCD'
export const GRAY_LIGHTEST = '#F1F1F1'
export const GRAY = '#707070'
export const ORANGE = '#F5A623'
export const TEAL = '#4285B9'
export const BUTTON_BLUE = '#4285B9'
export const TEXT_LIGHTEST = '#979797'
export const TEXT_LIGHT = '#787878'
export const TEXT_STANDARD = '#404040'
export const TEXT_WHITE = '#FFFFFF'
export const TEXT_ORANGE = '#F5A92B'
export const TEXT_GRAY = '#7B7B7B'
export const TEXT_GRAY_LIGHT = '#9A9696'
export const TEXT_GRAY_LIGHTER = '#9B9999'
export const TEXT_GRAY_LIGHTEST = '#B6B4B4'
export const TEXT_DARK_WHITE = '#b1b0b0'
export const ICON_GREEN = '#19ce5b'
export const ICON_RED = '#eb595e'
export const SUCCESS_GREEN = '#39B54A'
export const FAILURE_RED = '#C1272D'
export const CAUTION_YELLOW = '#EFC238'
export const TRANSPARENT = 'transparent'
export const TRANSPARENT_INPUT = 'rgba(0,0,0,0.05)'
export const LOADING_BACKDROP = 'rgba(0,0,0,0.25)'
export const GOLD = '#f2a900'
